packages:
  - 'apps/*'
  - 'packages/*'
blockExoticSubdeps: true
minimumReleaseAge: 10080
trustPolicy: no-downgrade
allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  unrs-resolver: true
  usb: true
overrides:
  '@node-escpos/usb-adapter>usb': '2.17.0'
